volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db_kitty:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: membranaa/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    depends_on:
      - db_kitty
  frontend:
    image: membranaa/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: membranaa/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media/
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
